{% set name = "mariadb-connector-c" %}
{% set version = "3.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mariadb-corporation/mariadb-connector-c/archive/v{{ version }}.tar.gz
  sha256: ced7e5063c91fe2bfafd9d63a759490fe53e81df80599a9abad01c570c202f0c

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - curl
    - git  # [not win]
  host:
    - zlib
    - zstd
    - krb5
    - libcurl
    - openssl
    - setuptools_dso  # [not win]
    - pykerberos  # [not win]

test:
  commands:
    - mariadb_config --version  # [not win]
    - my_print_defaults --version  # [win]

about:
  home: https://github.com/mariadb-corporation/mariadb-connector-c/
  summary: |
    MariaDB Connector/C is used to connect applications developed in C/C++ to MariaDB and MySQL databases.The client library is LGPL licensed. 
  description: |
    MariaDB Connector/C is used to connect applications developed in C/C++ to MariaDB and MySQL databases.The client library is LGPL licensed. 
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING.LIB
  dev_url: https://github.com/mariadb-corporation/mariadb-connector-c/

extra:
  recipe-maintainers:
    - avgra3
