{% set name = "mariadb-connector-c" %}
{% set version = "3.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mariadb-corporation/mariadb-connector-c/archive/v{{ version }}.tar.gz
  sha256: 4979916af92aaf7f7b09578897b7dd885d4acd9bfa8a6a0026334dbe98a0d2ab

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - curl
  host:
    - zlib  # [osx]
    - zstd
    - krb5  # [not win]
    - libcurl
    - openssl
    - setuptools_dso  # [not win]
    - python-kerberos  # [not win]

test:
  commands:
    - mariadb_config --version  # [not win]
    - my_print_defaults --version  # [win]

about:
  home: https://github.com/mariadb-corporation/mariadb-connector-c/
  summary: |
    MariaDB Connector/C is used to connect applications developed in C/C++ to MariaDB and MySQL databases.The client library is LGPL licensed. 
  description: |
    MariaDB Connector/C is used to connect applications developed in C/C++ to MariaDB and MySQL databases.The client library is LGPL licensed. 
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING.LIB
  dev_url: https://github.com/mariadb-corporation/mariadb-connector-c/

extra:
  recipe-maintainers:
    - avgra3
